# version: '3.8'

# services:
#   nuxt:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nuxt-app
#     restart: unless-stopped
#     expose:
#       - "8080"
#     environment:
#       - HOST=0.0.0.0
#       - PORT=8080
#       - NODE_ENV=production

#   nginx:
#     image: nginx:stable-alpine
#     container_name: nginx-proxy
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d
#       - ./certbot/www:/var/www/certbot
#       - ./certbot/conf:/etc/letsencrypt
#     depends_on:
#       - nuxt

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - ./certbot/www:/var/www/certbot
#       - ./certbot/conf:/etc/letsencrypt
